services:

  rhs-frontend:
    container_name: rms-frontend
    hostname: rms-frontend
    image: nginx:1.27.5
    volumes:
      - ./app/:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/local-js.sh:/docker-entrypoint.d/local-js.sh
    environment:
      SEARCH_API: "http://localhost:8081/search"
    ports:
      - "8080:80"
    healthcheck:
      test: curl --fail http://localhost/redis-movies-searcher || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    command: [ "/bin/sh", "-c", "chmod +x /docker-entrypoint.d/local-js.sh && /docker-entrypoint.sh nginx -g 'daemon off;'" ]

  redis-database:
    container_name: redis-database
    hostname: redis-database
    image: redis:8.0.2
    volumes:
      - ./data:/data
    environment:
      REDIS_ARGS: --save 30 1
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  redis-insight:
    container_name: redis-insight
    hostname: redis-insight
    image: redis/redisinsight:2.68
    depends_on:
      - redis-database
    environment:
      RI_REDIS_HOST: "redis-database"
      RI_REDIS_PORT: "6379"
    ports:
      - "5540:5540"
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -q -O- http://redis-insight:5540/api/health | grep -q '\"status\":\"up\"'"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
